# Generated by Django 5.2.7 on 2025-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='voter_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Voter ID'),
        ),
    ]
