# Generated by Django 5.2.7 on 2025-11-18 08:37

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='user_profile/user-icon.png', upload_to='user_profile', validators=[user.models.validate_file_size]),
        ),
    ]
