# Generated by Django 5.2.7 on 2025-11-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('USER', 'USER')], default='USER', max_length=20),
        ),
    ]
