# Generated by Django 5.2.7 on 2025-11-01 11:23

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import form.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RootForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('step_completed', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=12, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('current_step', models.PositiveSmallIntegerField(choices=[(0, 'Not completed any stpe'), (1, 'Personal Details'), (2, 'Service Details')], default=0, verbose_name='Current step')),
                ('form_number', models.CharField(default=form.models.generate_form_number, max_length=30, unique=True, verbose_name='Application number')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_form', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Root Form',
                'verbose_name_plural': 'Root Forms',
                'db_table': 'root_form',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, verbose_name='Gender')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile number')),
                ('pan_number', models.CharField(max_length=10, verbose_name='PAN number')),
                ('voter_id', models.CharField(blank=True, max_length=12, null=True, verbose_name='Voter ID')),
                ('is_step_completed', models.BooleanField(default=False, verbose_name='Is step completed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('root_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='form.rootform')),
            ],
            options={
                'verbose_name': 'Personal Details',
                'verbose_name_plural': 'Personal Details',
                'db_table': 'personal_details',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('joining_appointment_date', models.DateField()),
                ('regular_appointment_date', models.DateField(blank=True, null=True)),
                ('post_at_appointment', models.CharField(choices=[('revenue_clerk', 'Revenue Clerk'), ('revenue_talati', 'Revenue Talati'), ('deputy_mamlatdar', 'Deputy Mamlatdar')], max_length=50, verbose_name='Post at appointment')),
                ('ppan', models.CharField(blank=True, max_length=20, null=True, verbose_name='Permanent Pension Account Number (PPAN)')),
                ('pran', models.CharField(blank=True, max_length=20, null=True, verbose_name='Permanent Retirement Account Number (PRAN)')),
                ('is_step_completed', models.BooleanField(default=False, verbose_name='Is step completed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('root_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='form.rootform')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Service Details',
                'verbose_name_plural': 'Service Details',
                'db_table': 'service_details',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('exam_type', models.CharField(choices=[('pre_service', 'Pre Service Exam'), ('ccc', 'CCC Exam'), ('ccc_plus', 'CCC Plus Exam'), ('lrq', 'LRQ Exam'), ('hrq', 'HRQ Exam')], max_length=20)),
                ('passing_date', models.DateField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('service_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='form.servicedetails')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
