# Generated by Django 5.2.7 on 2025-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_personaldetails_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='pending', max_length=12, verbose_name='Status'),
        ),
    ]
